In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [3]:
iris = pd.read_csv("/kaggle/input/iris/Iris.csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
print("Target Labels", iris['Species'].unique())

Target Labels ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [6]:
fig = px.scatter(data_frame=iris, x='PetalWidthCm', y='PetalLengthCm', color='Species')
fig.show()

In [7]:
fig = px.scatter(data_frame=iris, x='SepalWidthCm', y='SepalLengthCm', color='Species')
fig.show()

In [8]:
x=iris.drop('Species',axis=1)
y=iris['Species']

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [9]:
knnModel=KNeighborsClassifier(n_neighbors=10)
knnModel.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=10)

In [10]:
ypredict=knnModel.predict(xtest)

In [11]:
confmat=confusion_matrix(ytest,ypredict)
print("Confusion Matrix :\n\n",confmat)

Confusion Matrix :

 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [12]:
acc=accuracy_score(ytest,ypredict)
print("Accuracy : {}%".format(round(acc*100,2)))

Accuracy : 96.67%


In [13]:
rep=classification_report(ytest,ypredict)
print(rep)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.86      1.00      0.92         6

       accuracy                           0.97        30
      macro avg       0.95      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30

